//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMenssagensErro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMenssagensErro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exceptions.ResourceMenssagensErro", typeof(ResourceMenssagensErro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao criar um novo usuário !.
        /// </summary>
        public static string ADICIAONAR_USER {
            get {
                return ResourceManager.GetString("ADICIAONAR_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar o usuário !.
        /// </summary>
        public static string ATUALIZAR_USER {
            get {
                return ResourceManager.GetString("ATUALIZAR_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar usuário por E-mail !.
        /// </summary>
        public static string BUSCA_ID_EMAIL {
            get {
                return ResourceManager.GetString("BUSCA_ID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar o Id do usuário !.
        /// </summary>
        public static string BUSCA_ID_USER {
            get {
                return ResourceManager.GetString("BUSCA_ID_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao deletar o usuário !.
        /// </summary>
        public static string DELETE_USER {
            get {
                return ResourceManager.GetString("DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse e-mail já existe na base de Dados!.
        /// </summary>
        public static string EMAIL_CADASTRADO {
            get {
                return ResourceManager.GetString("EMAIL_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail informado inválido.
        /// </summary>
        public static string EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido !.
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lista de usuários está vazia !.
        /// </summary>
        public static string LISTA_VAZIA {
            get {
                return ResourceManager.GetString("LISTA_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem registro na base de dados.
        /// </summary>
        public static string NOT_FOUND {
            get {
                return ResourceManager.GetString("NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password vazio!.
        /// </summary>
        public static string PASSWORD_BRANCO {
            get {
                return ResourceManager.GetString("PASSWORD_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password faltando caracter!.
        /// </summary>
        public static string PASSWORD_CARACTER {
            get {
                return ResourceManager.GetString("PASSWORD_CARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número do telefone inválido !.
        /// </summary>
        public static string PHONE_INVALIDO {
            get {
                return ResourceManager.GetString("PHONE_INVALIDO", resourceCulture);
            }
        }
    }
}
